### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by ocefpaf** [TEOS-10/GSW-Python#103]
@efiring and @DocOtak what do you think? It should not be too disruptive. Most of the projects I'm part of already moved away from the name master.

**Comment by DocOtak** [comment]
I've not taken an active role in this type of decision and will be happy with whatever is decided (or what my tools default to).

**Comment by efiring** [comment]
For the sake of adhering to the standard set by the git default--basically, for consistency--I'm OK with the change if you would like to execute it.

**Comment by ocefpaf** [comment]
Done!

**Comment by DocOtak** [comment]
I see a bunch of refs to "master" in the gh actions, do those need to be updated?

**Comment by ocefpaf** [comment]
> I see a bunch of refs to "master" in the gh actions, do those need to be updated?

See #105
