### ISSUE TITLE
No sdist on pypi?

### ISSUE THREAD

**Issue by hoodmane** [TEOS-10/GSW-Python#125]
Is there a reason that gsw-python does not publish an sdist to pypi?

**Comment by ocefpaf** [comment]
They are in https://pypi.org/project/gsw/3.6.16/#files

If you are looking only for the latest post1 release, those only affect the wheel, making it unnecessary to be there as sdist too b/c they would be identical to the 3.6.16.

**Comment by hoodmane** [comment]
> for the latest post1 release, those only affect the wheel

That was indeed what I was confused about. Thanks for the clarification!

**Comment by ocefpaf** [comment]
BTW, in that particular case, the two modifications in the post release are in the docs (that are not shipped in the tarball anyway) and a minor fix the pyodide wheel. We did not even needed that one in PyPI in retrospect, just pyodide.

See https://github.com/TEOS-10/GSW-Python/releases/tag/v3.6.16.post1
