### ISSUE TITLE
gsw.gibbs not seen

### ISSUE THREAD

**Issue by pvthinker** [TEOS-10/GSW-Python#128]
Dear authors,

I need to access the gibbs potential: gsw.gibbs but I can't. 'gibbs' is not in gsw.__dir__(). I've tempted several fixes: install from conda, git clone and compile from this site, using either Python3.7 or 3.8. In all cases, I've mostly all the functions but never the 'gibbs' one.

I installed gsw in a python2.7 environment and there you go, I see the gibbs function.

In all cases, I can see that gibbs is present in the dynamic library, but somethow _wrapped_ufuncs.py missed it

Help appreciated, thank you very much for this wonderful package.

Cheers,

Guillaume

**Comment by ocefpaf** [comment]
I believe this one can also be closed. If not please reopen.

xref.: #134
