### ISSUE TITLE
Add a "Development Instructions" README/Docs

### ISSUE THREAD

**Issue by ocefpaf** [TEOS-10/GSW-Python#129]
Currently we only have this note in our README:

    It is neither necessary nor recommended to run the code generators, and no instructions are provided for them;
    their output is included in the repo.

While I agree that the average user should not do that, we need to document those steps if we wish to lower the barrier for new developers.

It should be as simple as "promoting" the `tools/README.txt` to a first class citizen in our docs and/or linking it in our `README.md`.

**Comment by efiring** [comment]
Agreed.
