### ISSUE TITLE
add missing functions (gibbs etc)

### ISSUE THREAD

**Issue by pvthinker** [TEOS-10/GSW-Python#131]
Hello,

I was about to comment the #130 but you closed it before I could. I'm reopening an issue on the topic:

do you think it's worth I submit a PR to add gibbs to the package ?

My motivation. This morning my solution to include 'gibbs'  was a bit ugly. I've cleaned it. It is now very simple and it works well for gibbs. I can see that it could quite easily be generalized to the other missing functions.

**Comment by ocefpaf** [comment]
> I was about to comment the https://github.com/TEOS-10/GSW-Python/pull/130 but you closed it before I could.

Sorry about that but a new issue to is better to track this.

> do you think it's worth I submit a PR to add gibbs to the package ?

If you can see a path forward please do. I'm stuck with the day job today and won't be able to work on this until next week.

So far we have two choices:
1. Implement something similar to https://github.com/TEOS-10/GSW-Python/pull/24;
2. Modify [make_ufuncs.py](https://github.com/TEOS-10/GSW-Python/blob/main/tools/make_ufuncs.py) to include those functions.

@efiring did I capture your comments correctly above?

**Comment by pvthinker** [comment]
Yes,you capture my comment well.
I'm about to submit the PR
For the implementation, I'm following a third option, more like 1) than 2) but way shorter than 1).
