### ISSUE TITLE
Update zenodo?

### ISSUE THREAD

**Issue by rcaneill** [TEOS-10/GSW-Python#144]
Hello,
I would like to cite gsw-python in acknowledgement of a paper, but the zenodo link is quite old. Could one of the devs upload the last release to zenodo?
Thanks in advance!
Romain

**Comment by ocefpaf** [comment]
@rcaneill please take a look at the discussion in https://github.com/TEOS-10/GSW-C/issues/56. My impression is that individual DOI for the various GSW implementation is not what the authors of the base code want.

**Comment by rcaneill** [comment]
Thanks for pointing me to that discussion.
If I understand well, we only need to cite McDougall, T.J. and P.M. Barker, 2011: Getting started with TEOS-10 and the Gibbs Seawater (GSW) Oceanographic Toolbox, 28pp., SCOR/IAPSO WG127, ISBN 978-0-646-55621-5. 

Could this maybe be mentioned in the README of GSW-Python? If yes I can open a PR

**Comment by ocefpaf** [comment]
> Could this maybe be mentioned in the README of GSW-Python? If yes I can open a PR

That's my understanding too. I'm ok with a note in the readme.
