### ISSUE TITLE
conda-forge package?

### ISSUE THREAD

**Issue by rabernat** [TEOS-10/GSW-Python#22]
This package looks like a great improvement over the prior version. I am very pleased to see people working on this!

Providing a conda package via a [conda-forge recipe](https://conda-forge.org/#add_recipe) would help overcome the c-compiler issue you raised in the Readme and make it very easy for users to install the package. @ocefpaf knows quite a bit about how to do this...

**Comment by ocefpaf** [comment]
It is already packaged in conda-forge btw. Just install gsw from there.

**Comment by rabernat** [comment]
Ok sorry for the mistake. I recommend mentioning this in the readme and / or adding a badge. Otherwise it is hard to know this if you land on the github page.

**Comment by efiring** [comment]
Just be aware that the geostrophic streamfunction calculation has problems, which I am in the process of solving.  As far as I know, all the rest--the basic equation of state-related calculations--is OK.  I hope to get back to the streamfunction calculation in C, and get the revision finished within the month.

**Comment by rabernat** [comment]
@efiring thanks for the update!
I will be using this in my fall Intro to Physical Oceanography class for basic equation of state calculations...nothing so fancy as geostrophic streamfunction!

Thanks again for your important work on this package. A great service to the community.
