### ISSUE TITLE
Add the docs URL at the top on GitHub

### ISSUE THREAD

**Issue by ocefpaf** [TEOS-10/GSW-Python#31]
@efiring I don't have the rights here to do that but it would be nice to have the link https://TEOS-10.github.io/GSW-Python at the to like most projects do.

Here is a screeshot of it using my fork:

![screenshot from 2018-05-29 13-36-32](https://user-images.githubusercontent.com/950575/40672532-75d9f398-6345-11e8-851b-c963c39b1e3a.png)

PS: it helps some automated tools to find the docs too.

**Comment by efiring** [comment]
Good idea, thank you.  Done.

**Comment by ocefpaf** [comment]
Thanks!
