### ISSUE TITLE
Please package gsw/tests into the distribution tarball

### ISSUE THREAD

**Issue by mcepl** [TEOS-10/GSW-Python#39]
While packaging GSW for openSUSE, I would like to run test suite. For now I have packaged ``gsw/tests`` directory from the git repository myself, but it would be lovely if I could get it automatically from the distribution tarball. Thank you.

**Comment by ocefpaf** [comment]
The tests require some extra big binaries and packages to parse the matlab files.
I don't plan to bloat the PyPI source distribution with those files.

I recommend you to get the [source from git](https://github.com/TEOS-10/GSW-Python/releases/tag/v3.2.1) of you really need that.

**Comment by mcepl** [comment]
OK, thanks

**Comment by ocefpaf** [comment]
No problem. BTW, as a former OpenSUSE packager myself, I recommend switching to `conda` and `conda-forge` to install your packages ;-)
