### ISSUE TITLE
Error in geo_strf_dyn_height

### ISSUE THREAD

**Issue by zhang-c** [TEOS-10/GSW-Python#41]
Hello,

I try to use the geo_strf_dyn_height function in geostrophy.py, but it didn't work if p_ref is above the shallowest pressure. I think the code "if pgood[0] < p_ref:" means that p_ref is below the shallowest pressure. Therefore, it should be "if pgood[0] > p_ref:" instead. Thanks!

**Comment by efiring** [comment]
Good point, thank you.  I will fix it and add a test for this.
