### ISSUE TITLE
Difference results from geo_strf_dyn_height compared to Matlab version.

### ISSUE THREAD

**Issue by emmaworthington** [TEOS-10/GSW-Python#46]
I'm converting code from Matlab to Python, and calling gsw.geo_strf_dyn_height with the same conservative temperatures, absolute salinities, pressures and reference pressure as Matlab's gsw_geo_strf_dyn_height, however the two functions give different results. They are only comparable to 1 decimal place. I'm using the default interpolation method (pchip), linear interpolation gives results even more widely differing.
Is this expected behaviour?

**Comment by efiring** [comment]
The matlab version is a moving target so I don't expect exact agreement when interpolation comes into play, but the differences should be quite small unless the vertical sampling is extremely coarse.  Can you send me a zipfile or tarball with the data and scripts you are using and the results you are getting, preferably stripped down to just enough to show the different results? efiring at hawaii dot edu.

**Comment by emmaworthington** [comment]
Will do - is netcdf4 format OK?

**Comment by efiring** [comment]
Yes, netcdf4 is good.

**Comment by efiring** [comment]
Also, if you are working with a section, it's OK to send the whole section.  What matters in the end is the horizontal gradient, not the dynamic height at a point.

**Comment by emmaworthington** [comment]
Happy to close this issue following email discussion with @efiring. The differences between the Matlab and Python implementations are there (most likely due to different interpolation methods being used), but are small enough not to significantly affect the resulting transports calculated from them.
