### ISSUE TITLE
Broadcasting in p_from_z

### ISSUE THREAD

**Issue by chpelletier** [TEOS-10/GSW-Python#47]
I don't get the broadcasting rules used in `gsw.p_from_z` (for example). Suppose I have two 1D arrays, `depths` containing depth levels (size `nz`), `lats` containing latitudes (size `ny`). If I want to compute sea pressure at all `nz*ny` nodes located at each depth/latitude combination, how would I do? Broadcasting as I usually do in Numpy gives me a 1D array, which is not what I expected.

```
depths = np.array([-10., -500.])
latitudes = np.array([0., 30., 60.])

nz = np.size(depths)
ny = np.size(latitudes)

depths_casted = depths[:,None] * (np.ones(shape=[ny]))[None,:]
latitudes_casted = latitudes[None,:] * (np.ones(shape=[nz]))[:,None]
pres1 = gsw.p_from_z(z=depths_casted, lat=latitudes_casted)
print('pres1 input shapes', np.shape(depths_casted), np.shape(latitudes_casted))
print('pres1', pres1)
```
This outputs:
```
pres1 input shapes (2, 3) (2, 3)
pres1 [10.0554684  10.0687545  10.09541418]
```

If I "over-broadcast" the latitude array with an additional dummy dimension, the expected behaviour is obtained:
```
latitudes_overcasted = latitudes[None,None,:] * (np.ones(shape=[nz,1]))[:,:,None]
pres2 = gsw.p_from_z(z=depths_casted, lat=latitudes_overcasted)
print('pres2 input shapes', np.shape(depths_casted), np.shape(latitudes_overcasted))
print('pres2', pres2)
```
yields:
```
pres2 input shapes (2, 3) (2, 1, 3)
pres2 [[ 10.0554684   10.0687545   10.09541418]
 [503.37335332 504.03920542 505.37530014]]
```

Which is the same as if I had done a 2-level loop over `nz` and `ny`, and call p_from_z `nz*ny` times (which is expensive). Unless I am missing something, I would expect the `pres1` array to have shape `(2,3)` instead of just containing `pres2`'s first row. Is it a bug? Feature?

**Comment by efiring** [comment]
It's just standard numpy broadcasting. Try this:
```python
import numpy as np
import gsw
depths = np.array([-10., -500.])
latitudes = np.array([0., 30., 60.])
pres1 = gsw.p_from_z(depths[:, np.newaxis], latitudes[np.newaxis, :])
print(pres1.shape)
print(pres1)
```
yielding
```
(2, 3)
[[ 10.0554684   10.0687545   10.09541418]
 [503.37335332 504.03920542 505.37530014]]
```
It could even be simplified a bit because the second `np.newaxis` is unnecessary (but perhaps useful in this case for readability); numpy will add axes to the left as needed:
```python
pres2 = gsw.p_from_z(depths[:, np.newaxis], latitudes)
print(pres2)
```

**Comment by chpelletier** [comment]
Thanks.

I've realized that the problem was coming from using keyword arguments for `z` and `lat`. If I follow up from your example, and call `p_from_z` with explicitly specifying of the arguments, I reproduce the problem I originally had:
```
pres3 = gsw.p_from_z(z=depths[:,np.newaxis], lat = latitudes[np.newaxis,:])
print(pres3)
```
yielding:
```
array([ 10.0554684 ,  10.0687545 ,  10.09541418])
```

Is this an expected behaviour? Should I refrain from using keyword arguments (except `axis`)?

**Comment by efiring** [comment]
Almost all gsw functions make a sharp distinction between positional and keyword arguments.  They use a decorator that processes the positional arguments, and then they pass those processed arguments and the kwargs, if any, to a numpy ufunc.  At present any parameters that appear in the signature as positional should be considered as positional-only.  Eventually it may be possible to enforce this: https://www.python.org/dev/peps/pep-0570/.
