### ISSUE TITLE
Official Listing on teos-10.org

### ISSUE THREAD

**Issue by DocOtak** [TEOS-10/GSW-Python#51]
I had a good conversation with @PaulMBarker at OceanObs19. He expressed interest in having the python version listed on the [teos-10 software website](http://www.teos-10.org/software.htm). I'm not sure what the process would be. It looks like packages are hosted on that site directly, so probably just give them our "release" packages.

My guess is that most people are installing via conda-forge or pip, but having some "official" listing I think would make people happy for publication purposes.

**Comment by PaulMBarker** [comment]
Hi,
The time has come for me to update the software page on the TEOS10 website.
How should I add a link or note or ??? to point to the python version?
Paul.

**Comment by durack1** [comment]
@PaulMBarker this is where the conda (prepackaged python libraries, easy to install) live https://anaconda.org/conda-forge/gsw. V3.3.1 appears to be the latest version available in this repo https://github.com/TEOS-10/GSW-Python/releases

**Comment by efiring** [comment]
I presume this refers to this page: http://www.teos-10.org/software.htm.

I suggest adding something like this:

The Python version is developed at https://github.com/TEOS-10/GSW-Python, from which the latest source code can be downloaded.  For most users, however, using a conda-based Python distribution (miniconda, https://docs.conda.io/en/latest/miniconda.html, or Anaconda, https://www.anaconda.com/products/individual) is highly recommended.  The conda-forge channel provides the latest release, installable with a simple command: "conda install -c conda-forge gsw".

@ocefpaf and @DocOtak might have better suggestions for how to phrase it.

**Comment by PaulMBarker** [comment]
Yes, I did mean that page. thanks for your suggestion. I will use it if I do not get any better suggestion that you all prefer.

Paul.

**Comment by ocefpaf** [comment]
> @ocefpaf and @DocOtak might have better suggestions for how to phrase it.

That looks good to me. Thanks!

The package is also pip installable if you are OK compiling the source but most users who try that knows about it, I would not bother to add that to the page. I'd like to change the text only when we get wheels\* on PyPI.

\* pre-compiled binary distributions. I'm working on setting a CI to build that for us.

**Comment by DocOtak** [comment]
Having an actual zip distribution on the TEOS page would not be how the vast majority of users would install the toolbox. I'm with the wording and looking forward to having a wheel on pypi. I don't know what voodoo magic the netCDF4 python people are pulling, but their wheels have the C netCDF library itself embedded in it and things "just work" (at least in my docker containers).

Once listed, would there be justification of removing the "this implementation isn't official" scary text in the readme? This text:
>**Warning:** the only *official* TEOS-10 implementations are provided as zipfiles at <http://www.teos-10.org/software.htm>.

**Comment by DocOtak** [comment]
Just noticed #53 that seems to answer my "readme" question.

**Comment by ocefpaf** [comment]
@DocOtak wheels for `gsw` are actually easier to build than netcdf4-python b/c we don't need to bundle any external non-python library, just compiled on all platforms, test it, and :shipit:.

The main tool for that is [multibuild](https://github.com/matthew-brett/multibuild). That is the one used for netcdf4-python btw.

**Comment by PaulMBarker** [comment]
When the check functions was added and it was confirmed that the routines passed those functions the  "this implementation isn't official"  text could have been removed. 
I will modify the test to indicate that codes either downloaded or listed/inked from the teos-10 website are all official.

**Comment by efiring** [comment]
I think this is closed by the recent updates to the main website.
