### ISSUE TITLE
Wheels test

### ISSUE THREAD

**Issue by ocefpaf** [TEOS-10/GSW-Python#62]
I just installed the Windows wheels and ran the tests, all green 🎉 

@efiring or @DocOtak do you have a macOS to test them?
While we do test the code in the CIs I just want to be sure users will get the wheel and the tests will pass on a non-standard environment.

The wheels are in https://pypi.org/project/gsw/#files

~~PS: Linux wheels are not produced and uploaded yet. See #61. But I'm not in a hurry b/c Linux is by far the easiest one to install from source.~~

edit:
---

Linux are up and working too :tada:

**Comment by DocOtak** [comment]
For me on macOS 10.15, it successfully, and quickly, installed with `pip install gsw==3.3.1.post1` however I was unable to run the tests in situ using `pytest --pyargs gsw` due to the missing/excluded `gsw_check_functions_save.m` file from the wheel. When I manually put that file in the correct site-packages location, tests passed happily.

**Comment by ocefpaf** [comment]
> For me on macOS 10.15, it successfully, and quickly, installed with `pip install gsw==3.3.1.post1` however I was unable to run the tests in situ using `pytest --pyargs gsw` due to the missing/excluded `gsw_check_functions_save.m` file from the wheel. When I manually put that file in the correct site-packages location, tests passed happily.

That is not in the wheel and usually should bot be there. We would also need to ship the comparison data inflating its size. You'll have to run the tests against the source code, as you did :smile:

However, if it is only the `.m` that is missing we can ship it without increasing the size that much. I'll check if that is worth it.

PS: it will be odd to ship a python package with a matlab file :stuck_out_tongue_closed_eyes:

**Comment by DocOtak** [comment]
By my digital napkin calculations, It would add about 13k to the wheel, and about 110k to the installed size.

**Comment by ocefpaf** [comment]
Closing this. Thanks @DocOtak for testing it on macOS. We now have automated creation of wheels on Linux, macOS, and Windows. Note that only the Linux ones are automatically uploaded to PyPI. The other two platform will be uploaded as artifacts in the run, like this one https://github.com/TEOS-10/GSW-Python/actions/runs/227778225, and we will need to manually upload them to PyPI.

The reason for that manual upload is b/c the PyPA GH action only works on Linux and the other platforms require a not secure way to perform the upload. It cannot use the token but rather require the user and password and the secrets could be echoed but anyone with access to the TEOS-10 org. I don't want to make my PyPI credentials open ;-p
