### ISSUE TITLE
Citation/DOI

### ISSUE THREAD

**Issue by jbusecke** [TEOS-10/GSW-Python#71]
Hi everyone,

Many thanks for maintaining this important package. I am currently writing up a manuscript and would like to cite this package. Could you provide some guidance, how to do this best? I did not see a DOI right away.

Thanks

**Comment by DocOtak** [comment]
Hi @jbusecke, I believe the way to cite official implementations of TEOS-10 is by citing [the manual](http://www.teos-10.org/pubs/TEOS-10_Manual.pdf), see Appendix C (reproduced here):

>Note that when referring to the use of TEOS-10, it is the present document that should be referenced as IOC et al. (2010), with the full citation being
>>IOC, SCOR and IAPSO, 2010: The international thermodynamic equation of seawater – 2010: Calculation and use of thermodynamic properties. Intergovernmental Oceanographic Commission, Manuals and Guides No. 56, UNESCO (English), 196 pp.

**Comment by jbusecke** [comment]
Thank you very much for the quick reply @DocOtak!

**Comment by ocefpaf** [comment]
We can provide a DOI via zenodo for the latest code and the releases. It would help with provenance, etc. I'll look into it and add a badge to the README.

**Comment by jbusecke** [comment]
Thanks @ocefpaf. Ill make sure to put that into the final revision once available.

**Comment by ocefpaf** [comment]
> Thanks @ocefpaf. Ill make sure to put that into the final revision once available.

I added the badge to the README. Thanks for bringing this up!
