### ISSUE TITLE
Units / docsting issues

### ISSUE THREAD

**Issue by rcaneill** [TEOS-10/GSW-Python#92]
Hello,
while working on gsw-xarray we caught some errors in the units / docstrings. I list here what we found, if you agree on the correction I'll submit a PR:

* `rho_first_derivatives_wrt_enthalpy` : the whole docstring seems to be incorrect (cf [matlab doc](https://www.teos-10.org/pubs/gsw/html/gsw_rho_first_derivatives_wrt_enthalpy.html)). On top of this, the matlab doc unit is incorrect for rho_SA_wrt_h. Instead of `(kg/m^3)(g/kg)^-1 (J/kg)^-1` it should be `(kg/m^3)(g/kg)^-1` (this is d_rho / d_S)
* `rho_second_derivatives_wrt_enthalpy` : 
  * the unit of `rho_SA_SA` should be `(kg/m^3)(g/kg)^-2` (also incorrect in the matlab doc)
  * the unit of `rho_SA_h` should be `(kg/m^3)(g/kg)^-1 (J/kg)^-1` (correct in matlab doc)
  * the unit of `rho_h_h` should be `(kg/m^3)(J/kg)^-2` (correct in matlab doc)
* `specvol_first_derivatives_wrt_enthalpy` : unit of `v_SA_wrt_h` should be `(m^3/kg)(g/kg)^-1` (incorrect in the matlab doc)
* `specvol_second_derivatives` : unit of `v_SA_P` should be `(m^3/kg)(g/kg)^-1 Pa^-1`  (incorrect in the matlab doc)
* `specvol_second_derivatives_wrt_enthalpy` : unit of `v_SA_SA_wrt_h` should be `(m^3/kg)(g/kg)^-2` (incorrect in the matlab doc)

Unless I misunderstood something, these corrections should be good

**Comment by rcaneill** [comment]
I caught another typo:
* `cp_ice` : the docstring says "Calculates the isobaric heat capacity of seawater." instead of "Calculates the isobaric heat capacity of **ice**."

**Comment by rcaneill** [comment]
Hello,
I'm pinging on this issue, should I open a PR with the corrections I proposed?

**Comment by efiring** [comment]
The docstrings for these ufuncs are composed by parsing the matlab help text, which is automated.  Now and then, the matlab version being parsed is updated, at which point fixes to the matlab are inherited by the Python.  I'm reluctant to have changes made directly in the Python sources because they will just get clobbered the next time the sources are regenerated with a newer matlab version.  The best way to proceed would be to get the fixes into the matlab version and then use that newer version to regenerate the Python.  Even this is not trivial because subtle changes in the matlab routines and/or test data can cause it to get out of sync with the C code.

**Comment by rcaneill** [comment]
Ok, I don't do anything then

**Comment by richardsc** [comment]
Well at the very least these suggested corrections should be made for the Matlab version. Probably worth opening an issue there (though the tracked sources are not actually on GitHub).

**Comment by rcaneill** [comment]
> Well at the very least these suggested corrections should be made for the Matlab version. Probably worth opening an issue there (though the tracked sources are not actually on GitHub).

I agree but as the sources are not available, I haven't done it.
If you wish to raise the issue, please do so :)

**Comment by richardsc** [comment]
@PaulMBarker see the beginning of this thread for some issues and errors discovered in the Matlab help pages. Since there are no sources on GitHub to create a pull request, I thought it best to make you aware so they can be properly propagated into your version.

**Comment by PaulMBarker** [comment]
If anyone know of any other typos let me know as I have corrected these and will put up the corrected versions shortly.

**Comment by PaulMBarker** [comment]
I have updated the files to the TESO-10 website.
